
/'
 * Set Style Interface Component Arrow.
 * 
 * @param $cl class
 * @param $color color
'/
!procedure $setStyleIntCompArrow($cl, $color)
  <style>
    .$cl {
        LineColor $color
        BackgroundColor %darken($color, 10)
    }
  </style>
!endprocedure


/'
 * QuantumLog Interface Icon Component.
 *
 * @example
 *   $qlInterfaceIconComponent(K,red) as K {
 *     component B
 *   }
 * 
 * @param $name name
 * @param $color color
 * @param $scale scale
'/
!procedure $qlInterfaceIconComponent($name, $color, $scale=0.3)
  component "<$qlInterfaceIcon{scale=$scale,color=$color}> $name"
!endprocedure
