/'
 * QuantumLog
 * License: MIT
 * Source: https://github.com/JoeFerri/QuantumLog
 * Copyright (c) 2025 Giuseppe Ferri <jfinfoit@gmail.com>
'/

/'
 * Code
'/



'
' ConfigGradesCode
'
'''_______________________________________________
@startjson ql-code_configgradescode
!include ../code/ConfigGradesCode.json
@endjson


'
' ConfigRanksCode
'
'''_______________________________________________
@startjson ql-code_configrankscode
!include ../code/ConfigRanksCode.json
@endjson


'
' ConfigRoutesCode
'
'''_______________________________________________
@startjson ql-code_configroutescode
!include ../code/ConfigRoutesCode.json
@endjson