/'
 * QuantumLog
 * License: MIT
 * Source: https://github.com/JoeFerri/QuantumLog
 * Copyright (c) 2025 Giuseppe Ferri <jfinfoit@gmail.com>
'/

/'
 * Global view of the system.
'/



'''_______________________________________________
@startuml ql-components_main
!$title = "Components Main"
!$author = "Giuseppe Ferri"

!include templates/ql-template-main.puml
!include templates/styles/ql-style-lib.puml
!include templates/sprites/ql-sprites-lib.puml

skinparam linetype ortho
left to right direction

$qlSetLineBkgrColor(tomenu, Orange)
$qlSetLineBkgrColor(toexport, Navy)

rectangle r <<frame>> {

  '''_______________________________________________
  together {
    component [MainBoard]
      !$note = "Main program GUI."
      $qlNoteRel(nMainBoard, [MainBoard], ".", $note)

    $qlInterfaceIconComponent(MainMenu, Orange) as MainMenu
      interface IMainMenu1
        MainMenu - IMainMenu1
      interface IMainMenu2 <<tomenu>>
        MainMenu - IMainMenu2 <<tomenu>>
  }

  '''_______________________________________________
  component [PreferencesMenu]

  '''_______________________________________________
  component [StarMapDB]
    !$note = "Database of the game universe. Contains information and data on locations, labels, names, etc."
    $qlNoteRel(nStarMapDB, [StarMapDB], "..", $note)

  '''_______________________________________________
  component [TimeBoard]
    !$note = "Tools for collecting and analyzing time data."
    $qlNoteRel(nTimeBoard, [TimeBoard], "..", $note)

  '''_______________________________________________
  component [StarMapCargoRouteBoard]
    !$note = "GUI for displaying trade routes (possible, common or newly defined) in the game map."
    $qlNoteRel(nStarMapCargoRouteBoard, [StarMapCargoRouteBoard], "..", $note)

  '''_______________________________________________
  together {
    component [FilteredContractsListBoard]
    !$note = "Filtered list of transport contracts. Filtering is done through the Strategy component."
    $qlNoteRel(nFilteredContractsListBoard, [FilteredContractsListBoard], ".", $note)

    component [ContractsEntryBoard]
    !$note = "GUI (form) for entering the selected transport contracts."
    $qlNoteRel(nContractsEntryBoard, [ContractsEntryBoard], ".", $note)
      interface IContractsEntryBoard
        ContractsEntryBoard -l- IContractsEntryBoard
  }

  component [IncomeExpenseStatisticsBoard]

  '''_______________________________________________
  component [StrategyBoard]
    !$note = "GUI for strategy definition. It is composed of subcomponents that specialize in choosing/defining options and limits to be applied to either the contract list, route search and calculation algorithms, or cargo arrangement."
    $qlNoteRel(nStrategyBoard, [StrategyBoard], ".", $note)
  
  '''_______________________________________________
  together {
    component [CargoGrid]

    component [ShipDetails]
  }

  '''_______________________________________________
  together {
    component [FileSystem]
      interface IIO
        FileSystem -l- IIO

    $qlInterfaceIconComponent(DataExport, Navy) as DataExport
      interface IDataExport <<toexport>>
        DataExport -u- IDataExport <<toexport>>
  }

}


' relationships
MainBoard                    ->     IMainMenu1
DataExport                   ->     IIO
FilteredContractsListBoard   ->     IContractsEntryBoard
PreferencesMenu              ->     IDataExport           <<toexport>>
StarMapDB                    ->     IDataExport           <<toexport>>
FilteredContractsListBoard   ->     IDataExport           <<toexport>>
StrategyBoard                ->     IDataExport           <<toexport>>
PreferencesMenu              ->     IMainMenu2            <<tomenu>>
StarMapDB                    ->     IMainMenu2            <<tomenu>>
TimeBoard                    ->     IMainMenu2            <<tomenu>>
StarMapCargoRouteBoard       ->     IMainMenu2            <<tomenu>>
FilteredContractsListBoard   ->     IMainMenu2            <<tomenu>>
ContractsEntryBoard          ->     IMainMenu2            <<tomenu>>
StrategyBoard                ->     IMainMenu2            <<tomenu>>
StrategyBoard                ...>   CargoGrid   : use
StrategyBoard                ...>   ShipDetails : use

@enduml

'
'
'
'''_______________________________________________
@startuml ql-components_main_starmapdb
!$title = "StarMapDB"
!$author = "Giuseppe Ferri"

!include templates/ql-template-main.puml
!include templates/styles/ql-style-lib.puml

rectangle r <<frame>> {

  component [StarMapDB] {
    port PStarMapDBOut1
    port    PStarMapDBOut2

      component [StarMapDBCommon]
        !$note = "Central online database of the game universe."
        $qlNoteRel(nStarMapDBCommon, [StarMapDBCommon], ".l.", $note)

      component [StarMapDBPersonal]
        !$note = "Local (user's personal) offline database of the game universe."
        $qlNoteRel(nStarMapDBPersonal, [StarMapDBPersonal], ".l.", $note)

      StarMapDBCommon .. StarMapDBPersonal
  }
}

@enduml


'''_______________________________________________
@startuml ql-components_main_timeboard
!$title = "TimeBoard"
!$author = "Giuseppe Ferri"

!include templates/ql-template-main.puml
!include templates/styles/ql-style-lib.puml

rectangle r <<frame>> {

  component [TimeBoard] {
    port PTimeBoardOut

      component [TimeStatistics]
        !$note = "Shows time statistics of sessions, cycles, and single runs."
        $qlNoteRel(nTimeStatistics, [TimeStatistics], ".l.", $note)

      component [TimeTab]
        !$note = "GUI for capturing timestamps used in performance analysis of sessions, cycles, and single runs."
        $qlNoteRel(nTimeTab, [TimeTab], ".l.", $note)
  }

}

' top to bottom direction
TimeStatistics -[hidden]-> TimeTab

@enduml


'''_______________________________________________
@startuml ql-components_main_starmapcargorouteboard
!$title = "StarMapCargoRouteBoard"
!$author = "Giuseppe Ferri"

!include templates/ql-template-main.puml

rectangle r <<frame>> {

  component [StarMapCargoRouteBoard] {
    port PStarMapCargoRouteBoardOut

      component [3DStarMapCargoRoute]
      component [2DStarMapCargoRoute]
  }

}

' top to bottom direction
3DStarMapCargoRoute -[hidden]u-> 2DStarMapCargoRoute

@enduml