/'
 * QuantumLog
 * License: MIT
 * Source: https://github.com/JoeFerri/QuantumLog
 * Copyright (c) 2025 Giuseppe Ferri <jfinfoit@gmail.com>
'/

/'
 * The components described could be designed and developed in the future.
 * They are not necessary for the completion of the project nor is their development certain.
'/


@startuml ql-components_future_features
!$title = "Components Future Features"
!$author = "Giuseppe Ferri"

!include templates/ql-template-main.iuml



package qlFutureFeatures {
  [ServerAPI] as c01
  note right of c01
    A central online process/Thread Server stays listening for client calls from users.
    It offers APIs to communicate with the central database.
  end note

  [ClientAPI] as c02
  note right of c02
    API for local communication of Client software, i.e.,
    API for controlled modification (modding) of the program installed locally on the user's machine.
  end note

  [FreightJobBoard] as c03
  note right of c03
    GUI for supply/demand between couriers and merchants.
  end note

  [ArmedEscortRequestsBoard] as c04
  note right of c04
    GUI for requesting armed escorts from couriers/traders.
  end note

  [ArmedEscortOffersBoard] as c05
  note right of c05
    GUI for offering armed escorts by mercenaries to couriers/traders.
  end note

  [RouteFinder] as c06
  note right of c06
    Find an optimized run cycle from the defined strategy.
  end note

  [SessionSharingBoard] as c07
  note right of c07
    GUI for multiplayer management.
  end note
}

' top to bottom direction
c01 -[hidden]-> c02
c02 -[hidden]-> c03
c03 -[hidden]-> c04
c04 -[hidden]-> c05
c05 -[hidden]-> c06
c06 -[hidden]-> c07


@enduml