/'
 * QuantumLog
 * License: MIT
 * Source: https://github.com/JoeFerri/QuantumLog
 * Copyright (c) 2025 Giuseppe Ferri <jfinfoit@gmail.com>
'/

/'
 * Global view of the system.
'/



'
' Components Main
'
'''_______________________________________________
@startuml ql-components_main
!$title = "Components Main"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml
!include ../templates/sprites/ql-sprites-lib.iuml

skinparam linetype ortho
left to right direction

$qlSetLineBkgrColor(tomenu, Orange)
$qlSetLineBkgrColor(toexport, Navy)

rectangle r <<frame>> {

  '''_______________________________________________
  together {
    component [MainBoard]
      !$note = "Main program GUI."
      $qlNoteRel(nMainBoard, [MainBoard], ".", $note)

    $qlInterfaceIconComponent(MainMenu, Orange) as MainMenu
      interface IMainMenu1
        MainMenu - IMainMenu1
      interface IMainMenu2 <<tomenu>>
        MainMenu - IMainMenu2 <<tomenu>>
  }

  '''_______________________________________________
  component [PreferencesMenu]

  '''_______________________________________________
  component "[[ql-components_main_starmapdb.png {go to StarMapDB diagram} StarMapDB]]" as StarMapDB
    !$note = "Database of the game universe. Contains information and data on locations, labels, names, etc."
    $qlNoteRel(nStarMapDB, [StarMapDB], "..", $note)

  '''_______________________________________________
  component "[[ql-components_main_timeboard.png {go to TimeBoard diagram} TimeBoard]]" as TimeBoard
    !$note = "Tools for collecting and analyzing time data."
    $qlNoteRel(nTimeBoard, [TimeBoard], "..", $note)

  '''_______________________________________________
  component "[[ql-components_main_starmapcargorouteboard.png {go to StarMapCargoRouteBoard diagram} StarMapCargoRouteBoard]]" as StarMapCargoRouteBoard
    !$note = "GUI for displaying trade routes (possible, common or newly defined) in the game map."
    $qlNoteRel(nStarMapCargoRouteBoard, [StarMapCargoRouteBoard], "..", $note)

  '''_______________________________________________
  together {
    component [FilteredContractsListBoard]
    !$note = "Filtered list of transport contracts. Filtering is done through the Strategy component."
    $qlNoteRel(nFilteredContractsListBoard, [FilteredContractsListBoard], ".", $note)

    component [ContractsEntryBoard]
    !$note = "GUI (form) for entering the selected transport contracts."
    $qlNoteRel(nContractsEntryBoard, [ContractsEntryBoard], ".", $note)
      interface IContractsEntryBoard
        ContractsEntryBoard -l- IContractsEntryBoard
  }

  component [IncomeExpenseStatisticsBoard]
    !$note = "GUI for displaying statistics related to the income/expense account of a game session (freight session). Measured characteristics: aUEC/SCU, Time/aUEC, etc."
    $qlNoteRel(nIncomeExpenseStatisticsBoard, [IncomeExpenseStatisticsBoard], ".", $note)

  component [LoadingUnloadingBoard]
    !$note = "GUI for managing the loading/unloading of goods. Allows the choice of both algorithms for sorting cargo in the ship's hold and finding the best route between stations (the "+$qm()+"best"+$qm()+" feature depends on the needs defined in the game strategy)"
    $qlNoteRel(nLoadingUnloadingBoard, [LoadingUnloadingBoard], "..", $note)

  '''_______________________________________________
  component "[[ql-components_main_strategyboard.png {go to StrategyBoard diagram} StrategyBoard]]" as StrategyBoard
    !$note = "GUI for strategy definition. It is composed of subcomponents that specialize in choosing/defining options and limits to be applied to either the contract list, route search and calculation algorithms, or cargo arrangement."
    $qlNoteRel(nStrategyBoard, [StrategyBoard], ".", $note)
  
  '''_______________________________________________
  together {
    component [CargoGrid]

    component [ShipDetails]
  }

  '''_______________________________________________
  together {
    component [FileSystem]
      interface IIO
        FileSystem -l- IIO

    $qlInterfaceIconComponent(DataExport, Navy) as DataExport
      interface IDataExport <<toexport>>
        DataExport -u-- IDataExport <<toexport>>
  }

}

' relationships
MainBoard                       ->       IMainMenu1
DataExport                      ->       IIO
FilteredContractsListBoard      ->       IContractsEntryBoard
PreferencesMenu                 ->       IDataExport           <<toexport>>
StarMapDB                       ->       IDataExport           <<toexport>>
FilteredContractsListBoard      ->       IDataExport           <<toexport>>
StrategyBoard                   ->       IDataExport           <<toexport>>
LoadingUnloadingBoard           ->       IDataExport           <<toexport>>
TimeBoard                       ->       IDataExport           <<toexport>>
IncomeExpenseStatisticsBoard    ->       IDataExport           <<toexport>>
PreferencesMenu                 ->       IMainMenu2            <<tomenu>>
StarMapDB                       ->       IMainMenu2            <<tomenu>>
TimeBoard                       ->       IMainMenu2            <<tomenu>>
StarMapCargoRouteBoard          ->       IMainMenu2            <<tomenu>>
FilteredContractsListBoard      ->       IMainMenu2            <<tomenu>>
ContractsEntryBoard             ->       IMainMenu2            <<tomenu>>
StrategyBoard                   ->       IMainMenu2            <<tomenu>>
IncomeExpenseStatisticsBoard    ->       IMainMenu2            <<tomenu>>
LoadingUnloadingBoard           ->       IMainMenu2            <<tomenu>>
LoadingUnloadingBoard           ..>      CargoGrid                          : use
StrategyBoard                   .l..>    LoadingUnloadingBoard              : use
StrategyBoard                   .u.>     ShipDetails                        : use

@enduml


'
' StarMapDB
'
'''_______________________________________________
@startuml ql-components_main_starmapdb
!$title = "StarMapDB"
!$rootLink = "[[ql-components_main.png {go to Components Main diagram} Components Main]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [StarMapDB] {
    port PStarMapDBOut1
    port PStarMapDBOut2

      component [StarMapDBCommon]
        !$note = "Central online database of the game universe."
        $qlNoteRel(nStarMapDBCommon, [StarMapDBCommon], ".l.", $note)

      component [StarMapDBPersonal]
        !$note = "Local (user's personal) offline database of the game universe."
        $qlNoteRel(nStarMapDBPersonal, [StarMapDBPersonal], ".l.", $note)

      StarMapDBCommon .. StarMapDBPersonal
  }
}

@enduml


'
' TimeBoard
'
'''_______________________________________________
@startuml ql-components_main_timeboard
!$title = "TimeBoard"
!$rootLink = "[[ql-components_main.png {go to Components Main diagram} Components Main]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [TimeBoard] {
    port PTimeBoardOut

      component [TimeStatistics]
        !$note = "Shows time statistics of sessions, cycles, and single runs."
        $qlNoteRel(nTimeStatistics, [TimeStatistics], ".l.", $note)

      component [TimeTab]
        !$note = "GUI for capturing timestamps used in performance analysis of sessions, cycles, and single runs."
        $qlNoteRel(nTimeTab, [TimeTab], ".l.", $note)
  }

}

' top to bottom direction
TimeStatistics -[hidden]-> TimeTab

@enduml


'
' StarMapCargoRouteBoard
'
'''_______________________________________________
@startuml ql-components_main_starmapcargorouteboard
!$title = "StarMapCargoRouteBoard"
!$rootLink = "[[ql-components_main.png {go to Components Main diagram} Components Main]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [StarMapCargoRouteBoard] {
    port PStarMapCargoRouteBoardOut

      component [3DStarMapCargoRoute]
        !$note = "GUI for 3D visualization of trade routes in the game map."
        $qlNoteRel(n3DStarMapCargoRoute, [3DStarMapCargoRoute], ".l.", $note)

      component [2DStarMapCargoRoute]
        !$note = "GUI for 2D visualization of trade routes in the game map."
        $qlNoteRel(n2DStarMapCargoRoute, [2DStarMapCargoRoute], ".l.", $note)
  }

}

' top to bottom direction
3DStarMapCargoRoute -[hidden]u-> 2DStarMapCargoRoute

@enduml


'
' StrategyBoard
'
'''_______________________________________________
@startuml ql-components_main_strategyboard
!$title = "StrategyBoard"
!$rootLink = "[[ql-components_main.png {go to main components diagram} Components Main]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [StrategyBoard] {
    port StrategyBoardOut1
    port StrategyBoardOut2

      component [StartingEndingPoint]
        !$note = "Defining the starting and ending point of the session."
        $qlNoteRel(nStartingEndingPoint, [StartingEndingPoint], ".l.", $note)

      component "[[ql-components_main_limitsstrategy.png {go to LimitsStrategy diagram} LimitsStrategy]]" as LimitsStrategy
        !$note = "Numerical limits and ranges."
        $qlNoteRel(nLimitsStrategy, [LimitsStrategy], ".l.", $note)

      component "[[ql-components_main_shipstrategy.png {go to ShipStrategy diagram} ShipStrategy]]" as ShipStrategy
        !$note = "Parameters related to the ship used."
        $qlNoteRel(nShipStrategy, [ShipStrategy], ".l.", $note)


      component [CargoGrade]
        !$note = "<img:./../../out/ql-code/ql-code_cargogradecode.png{scale=1}>"
        $qlNoteRel(nCargoGrade, [CargoGrade], ".l.", $note)
'         note as ncCargoGrade
' <code>
'   !include code/CargoGradeCode.json
' </code>
'         end note
'         ncCargoGrade .l. nCargoGrade

      component [TransportGuildRank]
        !$note = "<img:./../../out/ql-code/ql-code_transportguildrankcode.png{scale=1}>"
        $qlNoteRel(nTransportGuildRank, [TransportGuildRank], ".l.", $note)
'         note as ncTransportGuildRank
' <code>
'   !include code/TransportGuildRankCode.json
' </code>
'         end note
'         ncTransportGuildRank .l. nTransportGuildRank

      component "[[ql-components_main_cargoroutestrategy.png {go to CargoRouteStrategy diagram} CargoRouteStrategy]]" as CargoRouteStrategy
        !$note = "<img:./../../out/ql-code/ql-code_cargoroutestrategycode.png{scale=1}>"
        $qlNoteRel(nCargoRouteStrategy, [CargoRouteStrategy], ".l.", $note)
'         note as ncCargoRouteStrategy
' <code>
'   !include code/CargoRouteStrategyCode.json
' </code>
'         end note
'         ncCargoRouteStrategy .l. nCargoRouteStrategy
  }

}

' top to bottom direction
StartingEndingPoint -[hidden]-> LimitsStrategy
LimitsStrategy -[hidden]-> ShipStrategy

CargoGrade -[hidden]-> TransportGuildRank
TransportGuildRank -[hidden]-> CargoRouteStrategy

@enduml


'
' LimitsStrategy
'
'''_______________________________________________
@startuml ql-components_main_limitsstrategy
!$title = "LimitsStrategy"
!$rootLink = "[[ql-components_main_strategyboard.png {go to StrategyBoard diagram} StrategyBoard]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [LimitsStrategy] {

      component [LimitsMaterial]
        !$note = "Limits on the type of materials."
        $qlNoteRel(nLimitsMaterial, [LimitsMaterial], ".l.", $note)

      component [LimitsAUec]
        !$note = "Interval aUec within which to filter the contracts in the list."
        $qlNoteRel(nLimitsAUec, [LimitsAUec], ".l.", $note)

      component [LimitsRoute]
        !$note = "Numerosity of loading/unloading stations by session and contract."
        $qlNoteRel(nLimitsRoute, [LimitsRoute], ".l.", $note)

      component [LimitsSCU]
        !$note = "SCU range within which to filter the contracts in the list. Maximum size of the crates. Numerosity of the crates."
        $qlNoteRel(nLimitsSCU, [LimitsSCU], ".l.", $note)
  }

}

' top to bottom direction
LimitsMaterial -[hidden]-> LimitsAUec
LimitsAUec -[hidden]-> LimitsRoute
LimitsRoute -[hidden]-> LimitsSCU

@enduml


'
' ShipStrategy
'
'''_______________________________________________
@startuml ql-components_main_shipstrategy
!$title = "ShipStrategy"
!$rootLink = "[[ql-components_main_strategyboard.png {go to StrategyBoard diagram} StrategyBoard]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [ShipStrategy] {

      component [ShipOptions]
        !$note = "Selection of ship components."
        $qlNoteRel(nShipOptions, [ShipOptions], ".l.", $note)

      component [CargoGridStrategy]
        !$note = "Choice of loading strategy, i.e., placement of boxes on the grid (choice of algorithm)."
        $qlNoteRel(nCargoGridStrategy, [CargoGridStrategy], ".l.", $note)

      component [ShipDetailsStrategy]
        !$note = "View of the details of the ship influenced by the components."
        $qlNoteRel(nShipDetailsStrategy, [ShipDetailsStrategy], ".l.", $note)
  }

}

' top to bottom direction
ShipOptions -[hidden]-> CargoGridStrategy
CargoGridStrategy -[hidden]-> ShipDetailsStrategy

@enduml


'
' CargoRouteStrategy
'
'''_______________________________________________
@startuml ql-components_main_cargoroutestrategy
!$title = "CargoRouteStrategy"
!$rootLink = "[[ql-components_main_strategyboard.png {go to StrategyBoard diagram} StrategyBoard]]"
!$author = "Giuseppe Ferri"

!include ../templates/ql-template-main.iuml
!include ../templates/styles/ql-style-lib.iuml

rectangle r <<frame>> {

  component [CargoRouteStrategy] {

      component [CargoRouteSimple]
        !$note = "Selection from one of the routes specified in the HaulCargo_CargoRoute field (see <b>CargoRouteStrategyCode.json</b>)"
        $qlNoteRel(nCargoRouteSimple, [CargoRouteSimple], ".l.", $note)

      component [CargoRouteMore]
        !$note = "More refined filtering of route strategy."
        $qlNoteRel(nCargoRouteMore, [CargoRouteMore], ".l.", $note)
  }

}

' top to bottom direction
CargoRouteSimple -[hidden]-> CargoRouteMore

@enduml

