!include ../ql-semver.iuml
!include styles/ql-style-main.iuml
!include headers/ql-header-main.iuml
!include footers/ql-footer-main.iuml
!include titles/ql-title-main.iuml
!include captions/ql-caption-main.iuml